### PR TITLE
Fix filter

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by M0ses** [comment]
Comment from @thkukuk:

```
(^kubic|^opensuse/([^/]+)$)
```
seems to be the better approach

**Comment by mlschroe** [comment]
You probably should check the 'distmanifesttype' entry and create different types of manifests from the info.json file (the type can be 'list' or 'image')

**Comment by mlschroe** [comment]
OTOH it's probably better to not emulate the "fetch the manifest" way 100%.

**Comment by mlschroe** [comment]
(The "manifest" part is not used in details.tt2 anyway if `use_obs_extended_info` is true, so all this is moot anyway ;-) )

**Pull request merged**
